In [1]:
import networkx as nx
import pandas as pd

path_to_dir = '../data/processed_data/'

In [29]:
# Load the necessary data (Replace with your actual data loading mechanism)
stations = pd.read_csv(path_to_dir + 'stations.csv')  # Contains station info like id, name, latitude, longitude, etc.
routes = pd.read_csv(path_to_dir + 'routes.csv')  # Contains route info like route_id, start station, end station
stop_times = pd.read_csv(path_to_dir + 'stop_times.csv')  # Contains stop sequence and distances between stations
shapes = pd.read_csv(path_to_dir + 'shapes.csv') # Contains info like shape_id, shape_pt_sequence etc.

In [30]:
stations.head()

,station_id,station_name,metro_line,routes,latitude,longitude,station_type
0,21,Rithala,Red Line,"[0, 1, 18, 19]",28.720821,77.105042,Terminal
1,20,Rohini West,Red Line,"[0, 1, 18, 19]",28.715008,77.115746,Normal
2,19,Rohini East,Red Line,"[0, 1, 18, 19]",28.707941,77.125732,Normal
3,18,Pitampura,Red Line,"[0, 1, 18, 19]",28.703180,77.132355,Normal
4,17,Kohat Enclave,Red Line,"[0, 1, 18, 19]",28.697943,77.140465,Normal

In [32]:
# Create a graph object
metro_graph = nx.Graph()

# Adding nodes (stations)
for index, row in stations.iterrows():
    station_id = row['station_id']
    station_name = row['station_name']
    metro_line = row['metro_line']
    latitude = row['latitude']
    longitude = row['longitude']
    station_type = row['station_type']  # Elevated, Underground, At-Grade

    # Adding station as a node with attributes
    metro_graph.add_node(station_id, name=station_name, line=metro_line, 
                         lat=latitude, lon=longitude, type=station_type)

In [69]:
complete_routes = routes[routes['route_type'] == 'Complete']['route_id'].tolist()

# Add Aqua line to the complete_routes
complete_routes.extend([34, 35])

print(complete_routes)

[1, 2, 5, 6, 7, 10, 11, 12, 13, 14, 15, 19, 20, 23, 24, 25, 28, 29, 30, 31, 32, 33, 34, 35]

In [78]:
complete_shapes = shapes[shapes['route_id'].isin(complete_routes)].sort_values(by=('route_id'))

complete_shapes.head()

,shape_id,route_id,metro_line,shape_pt_sequence,shape_pt_lat,shape_pt_lon,shape_dist_traveled
5139,shp_1_32,1,Red Line,114,28.667650,77.230080,15077.797
5189,shp_1_32,1,Red Line,164,28.670000,77.267479,19028.127
5190,shp_1_32,1,Red Line,165,28.670050,77.267784,19058.238
5191,shp_1_32,1,Red Line,166,28.670015,77.267807,19062.383
5192,shp_1_32,1,Red Line,167,28.670059,77.267975,19079.910

In [79]:
stop_times

,trip_id,station_id,station_sequence,arrival_time,departure_time,shape_dist_traveled
0,0,21,0,05:28:08,05:28:28,0.000
1,0,20,1,05:30:58,05:31:18,1202.405
2,0,19,2,05:33:28,05:33:48,2480.750
3,0,18,3,05:35:33,05:35:53,3314.936
4,0,17,4,05:37:53,05:38:13,4300.216
...,...,...,...,...,...,...
128429,17548,512,8,22:14:55,22:15:15,11954.803
128430,17548,511,9,22:17:15,22:17:35,13655.823
128431,17548,510,10,22:19:35,22:19:55,14878.926
128432,17548,509,11,22:21:55,22:22:15,16252.104
128433,17548,508,12,22:24:15,22:24:35,17323.963

In [80]:
routes

,route_id,metro_line,route_name,route_start,route_end,route_type,stations,interchangeStations,shape_id
0,0,Red Line,Rithala to Dilshad Garden,Rithala,Dilshad Garden,Partial,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","['Welcome', 'Kashmere Gate', 'Inderlok', 'Neta...",shp_1_30
1,1,Red Line,Rithala to Shaheed Sthal (New Bus Adda),Rithala,Shaheed Sthal (New Bus Adda),Complete,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","['Welcome', 'Kashmere Gate', 'Inderlok', 'Neta...",shp_1_32
2,2,Yellow Line,Huda City Centre to Samaypur Badli,Huda City Centre,Samaypur Badli,Complete,"[8, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46...","['Kashmere Gate', 'Azadpur', 'New Delhi', 'Raj...",shp_1_13
3,3,Yellow Line,Qutab Minar to Vishwavidyalaya,Qutab Minar,Vishwavidyalaya,Partial,"[8, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54...","['Kashmere Gate', 'New Delhi', 'Rajiv Chowk', ...",shp_1_25
4,4,Yellow Line,Huda City Centre to Qutab Minar,Huda City Centre,Qutab Minar,Partial,"[64, 65, 66, 67, 68, 69, 70, 71, 62, 63]",['Sikanderpur'],shp_1_9
5,5,Blue Line,Dwarka Sector - 21 to Noida Electronic City,Dwarka Sector - 21,Noida Electronic City,Complete,"[233, 234, 235, 236, 237, 238, 50, 79, 80, 81,...","['Rajiv Chowk', 'Botanical Garden', 'Mayur Vih...",shp_1_14
6,6,Blue Line,Dwarka Sector - 21 to Vaishali,Dwarka Sector - 21,Vaishali,Complete,"[50, 72, 73, 74, 75, 76, 77, 78, 89, 90, 91, 9...","['Rajiv Chowk', 'Anand Vihar', 'Karkarduma', '...",shp_1_12
7,7,Green Line,Kirti Nagar to Brigadier Hoshiyar Singh,Kirti Nagar,Brigadier Hoshiyar Singh,Complete,"[22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 3...",['Kirti Nagar'],shp_1_17
8,8,Green Line,Inderlok to Brigadier Hoshiyar Singh,Inderlok,Brigadier Hoshiyar Singh,Partial,"[13, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 3...",['Inderlok'],shp_1_11
9,9,Violet Line,Kashmere Gate to Badarpur Border,Kashmere Gate,Badarpur Border,Partial,"[128, 129, 130, 131, 132, 133, 134, 135, 8, 13...","['Kalkaji Mandir', 'Kashmere Gate', 'Central S...",shp_1_15
10,10,Violet Line,Kashmere Gate to Raja Nahar Singh,Kashmere Gate,Raja Nahar Singh,Complete,"[128, 129, 130, 131, 132, 133, 134, 135, 8, 13...","['Kalkaji Mandir', 'Kashmere Gate', 'Central S...",shp_1_19
11,11,Pink Line,Majlis Park to Shiv Vihar,Majlis Park,Shiv Vihar,Complete,"[5, 16, 41, 173, 174, 175, 176, 177, 178, 179,...","['Welcome', 'Netaji Subash Place', 'Azadpur', ...",shp_1_26
12,12,Magenta Line,Janak Puri West to Botanical Garden,Janak Puri West,Botanical Garden,Complete,"[131, 161, 162, 163, 164, 165, 166, 167, 182, ...","['Kalkaji Mandir', 'Hauz Khas', 'Botanical Gar...",shp_1_16
13,13,Gray Line,Dwarka to Dhansa Bus Stand,Dwarka,Dhansa Bus Stand,Complete,"[240, 113, 241, 239]",['Dwarka'],shp_1_2
14,14,Orange/airport Line,Dwarka Sector - 21 to New Delhi,Dwarka Sector - 21,New Delhi,Complete,"[49, 121, 154, 155, 156, 157]","['New Delhi', 'Dwarka Sector - 21']",shp_1_7
15,15,Rapid Line,Sector 55-56 (Rapid Metro) to Phase 3 (Rapid M...,Sector 55-56 (Rapid Metro),Phase 3 (Rapid Metro),Complete,"[68, 168, 169, 170, 171, 172, 148, 149, 150, 1...",['Sikanderpur'],shp_1_29
16,16,Aqua Line,Noida Sector 51 to Noida Sector 142,Noida Sector 51,Noida Sector 142,Partial,"[500, 501, 502, 503, 504, 505, 506, 507, 508]",[],shp_1_23
17,17,Aqua Line,Noida Sector 142 to Depot Station,Noida Sector 142,Depot Station,Partial,"[512, 513, 514, 515, 516, 517, 518, 519, 520, ...",[],shp_1_21
18,18,Red Line,Dilshad Garden to Rithala,Dilshad Garden,Rithala,Partial,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","['Welcome', 'Kashmere Gate', 'Inderlok', 'Neta...",shp_1_6
19,19,Red Line,Shaheed Sthal (New Bus Adda) to Rithala,Shaheed Sthal (New Bus Adda),Rithala,Complete,"[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","['Welcome', 'Kashmere Gate', 'Inderlok', 'Neta...",shp_1_33
20,20,Yellow Line,Samaypur Badli to Huda City Centre,Samaypur Badli,Huda City Centre,Complete,"[8, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46...","['Kashmere Gate', 'Azadpur', 'New Delhi', 'Raj...",shp_1_31
21,21,Yellow Line,Vishwavidyalaya to Qutab Minar,Vishwavidyalaya,Qutab Minar,Partial,"[8, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54...","['Kashmere Gate', 'New Delhi', 'Rajiv Chowk', ...",shp_1_34
22,22,Yellow Line,Qutab Minar to Huda City Centre,Qutab Minar,Huda City Centre,Partial,"[64, 65, 66, 67, 68, 69, 70, 71, 62, 63]",['Sikanderpur'],shp_1_22
23,23,Blue Line,Noida Electronic City to Dwarka Sector - 21,Noida Electronic City,Dwarka Sector - 21,Complete,"[50, 119, 120, 79, 80, 81, 82, 83, 84, 85, 86,...","['Rajiv Chowk', 'Botanical Garden', 'Mayur Vih...",shp_1_28
24,24,Blue Line,Vaishali to Dwarka Sector - 21,Vaishali,Dwarka Sector - 21,Complete,"[50, 72, 73, 74, 75, 76, 77, 78, 89, 90, 91, 9...","['Rajiv Chowk', 'Anand Vihar', 'Karkarduma', '...",shp_1_36
25,25,Green Line,Brigadier Hoshiyar Singh to Kirti Nagar,Brigadier Hoshiyar Singh,Kirti Nagar,Complete,"[22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 3...",['Kirti Nagar'],shp_1_4
26,26,Green Line,Brigadier Hoshiyar Singh to Inderlok,Brigadier Hoshiyar Singh,Inderlok,Partial,"[13, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 3...",['Inderlok'],shp_1_3
27,27,Violet Line,Badarpur Border to Kashmere Gate,Badarpur Border,Kashmere Gate,Partial,"[128, 129, 130, 131, 132, 133, 134, 135, 136, ...","['Kalkaji Mandir', 'Kashmere Gate', 'Central S...",shp_1_5
28,28,Violet Line,Raja Nahar Singh to Kashmere Gate,Raja Nahar Singh,Kashmere Gate,Complete,"[128, 129, 130, 131, 132, 133, 134, 135, 136, ...","['Kalkaji Mandir', 'Kashmere Gate', 'Central S...",shp_1_27
29,29,Pink Line,Shiv Vihar to Majlis Park,Shiv Vihar,Majlis Park,Complete,"[5, 16, 41, 173, 174, 175, 176, 177, 178, 179,...","['Welcome', 'Netaji Subash Place', 'Azadpur', ...",shp_1_35
30,30,Magenta Line,Botanical Garden to Janak Puri West,Botanical Garden,Janak Puri West,Complete,"[131, 161, 162, 163, 164, 165, 166, 167, 182, ...","['Kalkaji Mandir', 'Hauz Khas', 'Botanical Gar...",shp_1_8
31,31,Gray Line,Dhansa Bus Stand to Dwarka,Dhansa Bus Stand,Dwarka,Complete,"[240, 241, 113, 239]",['Dwarka'],shp_1_1
32,32,Orange/airport Line,New Delhi to Dwarka Sector - 21,New Delhi,Dwarka Sector - 21,Complete,"[49, 121, 154, 155, 156, 157]","['New Delhi', 'Dwarka Sector - 21']",shp_1_18
33,33,Rapid Line,Phase 3 (Rapid Metro) to Sector 55-56 (Rapid M...,Phase 3 (Rapid Metro),Sector 55-56 (Rapid Metro),Complete,"[68, 168, 169, 170, 171, 172, 148, 149, 150, 1...",['Sikanderpur'],shp_1_24
34,34,Aqua Line,Noida Sector 142 to Noida Sector 51,Noida Sector 142,Noida Sector 51,Partial,"[500, 501, 502, 503, 504, 505, 506, 507, 508]",[],shp_1_20
35,35,Aqua Line,Depot Station to Noida Sector 142,Depot Station,Noida Sector 142,Partial,"[512, 513, 514, 515, 516, 517, 518, 519, 520, ...",[],shp_1_10